import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import localFont from "next/font/local";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Team TIG vote FE',
  description: 'Generated by Team TIG Frontend and Backend',
  icons: {
    icon: '/tig.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-full h-screen flex flex-col items-center ${pretendard.className} font-pretendard`}
      >
        {children}
      </body>
    </html>
  );
}
